### PR TITLE
feat: display exported icons

### LINKED ISSUE #76: 🐛 Bug Report: Some icons from heroicons dont work
### 👟 Reproduction steps

- `"@appwrite.io/pink-icons"` to your project
- use `<div class="icon-login"></div>`

### 👍 Expected behavior

this icon should appear
image

### 👎 Actual Behavior

It's an empty div

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

@appwrite.io/pink - 0.0.6-rc.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by TGlide**
## What does this PR do?

Displays the exported icons on the docs, instead of just linking to heroicons.

## Test Plan

Manual

## Related PRs and Issues

Closes #76 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by ArmanNik** [comment]
@TGlide We might want to filter the custom icons from the general icons, no sense in repeating them :thinking:

**Comment by TGlide** [comment]
@ArmanNik can you re-review? 😄

**Review by ArmanNik — APPROVED** [review]
LGTM unless we also want to add the click to copy feature :+1:

**Comment by TGlide** [comment]
> LGTM unless we also want to add the click to copy feature 👍

I'll deal with it in the separate PR 🙂

**Pull request merged**
